version: '3.9'

name: smart-home-conx-api

networks:
  default:
    driver: bridge
    name: smart-home-conx-api

services:
  backend01:
    image: backend:local-build
    build:
      context: .
    expose:
      - 3001

  backend02:
    image: backend:local-build
    build:
      context: .
    expose:
      - 3001

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend01
      - backend02
    ports:
      - 4000:4000